spring:
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      dll-auto: create-drop
      naming:     
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  datasource:
    url: jdbc:mysql://localhost:3306/financial_app?useTimezone=true&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
conta:
  abertura:
    valorMinimo: 50

microservice:
  depositar:
    url: "http://localhost:8080/api/"