openapi: 3.0.0
info:
  version: '1.0.0'
  title: 'Transacoes'
  license:
    name: MIT
servers:
  - url: 'localhost:3000'
paths:
  /transacoes:
    post:
      summary: 'Sample endpoint: Cria uma transação bancária'
      operationId: criarTransacao
      tags:
        - transacoes
      requestBody:
        content: 
          application/vnd.transacoes.v1+json:
            schema:
              $ref: "#/components/schemas/Transacao"
      responses:
        '201':
          description: 'Sample response: Retorna um link com o id criado da transacao para que possa ser consultado essa transacao em específico.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SucessoResponse'
        '400':
          description: 'Sample response: Quando não informado um campo obrigatório'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErroResponse'
        '404':
          description: 'Sample response: Retonado se não for encontrado o cpf ou a conta origem'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErroResponse'
        '500':
          description: 'Sample response: Erro interno'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErroResponse'
components:
  schemas:
    Transacao:
      type: object
      required: 
        - cpf
        - contaDestino
        - valor
        - tipo
      properties:
        cpf:
            description: "identificador do correntista da conta de origem"
            type: object
            $ref: '#/components/schemas/Cpf'
        contaDestino: 
            description: "Objeto que contém as informações de uma conta de destino, de onde o dinheiro será depositado"
            type: object
            $ref: '#/components/schemas/Conta'
        valor:
            type: object
            $ref: '#/components/schemas/Valor'
        tipo:
            type: object
            $ref: "#/components/schemas/Tipo"
    Cpf:
      type: object
      properties:
        documento:
          type: string
    ContaDestino:
      type: object
      properties:
        cpf:
          type: object
          $ref: '#/components/schemas/Cpf'
        conta:
          type: object
          $ref: '#/components/schemas/Conta'
    Conta:
      type: object
      properties:
        banco:
          type: integer
        agencia:
          type: integer
        numero:
          type: integer
        digito:
          type: integer
    Valor:
      type: object
      properties:
        total:
          type: number
          format: bigdecimal
    Tipo:
        type: string
        enum: [DOC, TED, PIX]
    SucessoResponse:
      type: object
      properties:
        mensagem: 
          type: string
          description: Mensagem de sucesso ao realizar a operação
        _links:
          type: object
          $ref: '#/components/schemas/Links'
    Links: 
      type: array
      items:
          $ref: '#/components/schemas/HateoasResponse'
    HateoasResponse:
      type: object
      required:
        - href
        - type
      properties:
          href:
            type: string
            description: "URI retornada para ter acesso a proxima operacao"
          type:
            type: string
            description: "Metodo a ser utilizado para consultar o a URI retornada no campo href"
    ErroResponse:
      type: object
      properties:
        codigo:
          type: string
          description: 'Código retornado referente ao erro'
        mensagem:
          type: string
          description: 'Mensagem de erro retornada referente ao erro'
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
security:
  - BasicAuth: []